# -*- mode: ruby -*-

VAGRANTFILE_API_VERSION = "2"

module Vagrant
  module Config
    module V2
      class Root
        def provision()
          vm.provision "ansible" do |ansible|
            ansible.playbook = "playbook.yml"
            ansible.extra_vars = { ansible_ssh_user: 'ubuntu' }
          end
        end
      end
    end
  end
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provision "shell", inline: "sudo apt-get update && sudo apt-get install -y python"

  config.provision()
end
