import factory
import hashlib

from factory import Sequence
from factory.alchemy import SQLAlchemyModelFactory

from server.webapp.dbmodels import ParsetsDb
from server.webapp.dbmodels import ProgramsDb
from server.webapp.dbmodels import ProjectDataDb
from server.webapp.dbmodels import ProjectDb, ProgsetsDb
from server.webapp.dbmodels import ResultsDb
from server.webapp.dbmodels import UserDb
from server.webapp.dbmodels import WorkLogDb
from server.webapp.dbmodels import WorkingProjectDb

from sqlalchemy import create_engine
from sqlalchemy.orm import scoped_session, sessionmaker

engine = create_engine('postgresql+psycopg2://test:test@localhost:5432/optima_test')
session = scoped_session(sessionmaker(bind=engine))

class BaseFactory(SQLAlchemyModelFactory):
    class Meta:
        sqlalchemy_session = session

class UserFactory(BaseFactory):

    class Meta:
        model = UserDb

    name = 'test'
    email = Sequence(lambda n: 'user_{}@test.com'.format(n))
    password = hashlib.sha224("test").hexdigest()
    is_admin = False


class ProjectFactory(BaseFactory):

    class Meta:
        model = ProjectDb

    name = factory.Faker('name')
    user_id = UserFactory().id
    datastart = 2000
    dataend = 2030
    populations = [{"name": "Female sex workers", "short_name": "FSW", "sexworker": True, "injects": False, "sexmen": True, "client": False, "female": True, "male": False, "sexwomen": False}, \
            {"name": "Clients of sex workers", "short_name": "Clients", "sexworker": False, "injects": False, "sexmen": False, "client": True, "female": False, "male": True, "sexwomen": True}, \
            {"name": "Men who have sex with men", "short_name": "MSM", "sexworker": False, "injects": False, "sexmen": True, "client": False, "female": False, "male": True, "sexwomen": False}, \
            {"name": "Males who inject drugs", "short_name": "Male PWID", "sexworker": False, "injects": True, "sexmen": False, "client": False, "female": False, "male": True, "sexwomen": True}, \
            {"name": "Other males [enter age]", "short_name": "Other males", "sexworker": False, "injects": False, "sexmen": False, "client": False, "female": False, "male": True, "sexwomen": True}, \
            {"name": "Other females [enter age]", "short_name": "Other females", "sexworker": False, "injects": False, "sexmen": True, "client": False, "female": True, "male": False, "sexwomen": False}]
    version = '2.0'


class ParsetFactory(BaseFactory):

    """
        Requires a project that can be generated by calling the
        ProjectFactory()
        example usage:
        project = ProjectFactory()
        ParsetFactory(project_id=parset.project_id)
    """
    class Meta:
        model = ParsetsDb

    project_id = factory.LazyAttribute(lambda n: n)
    name = factory.Faker('name')


class ResultFactory(BaseFactory):

    """
        Requires a parset that can be generated by calling the ParsetFactory()
        example usage:
        parset = ParsetFactory()
        ResultFactory(parset_id=parset.id, project_id=parset.project_id)
    """
    class Meta:
        model = ResultsDb

    parset_id = factory.LazyAttribute(lambda n: n)
    project_id = factory.LazyAttribute(lambda n: n)
    calculation_type = 'simulation'


class WorkingProjectFactory(BaseFactory):

    """
        Takes in an is_working attribute of Boolean type
        example usage:
        WorkingProjectFactory(is_working=True)
    """
    class Meta:
        model = WorkingProjectDb

    is_working = factory.LazyAttribute(lambda n: n)


class WorkLogFactory(BaseFactory):

    class Meta:
        model = WorkLogDb

    project_id = ProjectFactory()


class ProjectDataFactory(BaseFactory):

    """
        Requires a project that can be generated by calling the
        ProjectFactory()
        example usage:
        project = ProjectFactory()
        ProjectDataFactory(id=project.id)
    """
    class Meta:
        model = ProjectDataDb

    id = factory.LazyAttribute(lambda n: n)


class ProgsetsFactory(BaseFactory):

    """
        Requires a project that can be generated by calling the
        ProjectFactory()
        example usage:
        project = ProjectFactory()
        ProgsetFactory(project_id=project.id)
    """
    class Meta:
        model = ProgsetsDb
    project_id = factory.LazyAttribute(lambda n: n)
    name = factory.Faker('name')


class ProgramsFactory(BaseFactory):

    """
        Requires a project and a progsetthat can be generated by calling the
        ProjectFactory() and ProgsetFactory
        example usage:
        project = ProjectFactory()
        progset = ProgsetFactory(project_id=project.id)
        ProgramsFactory(progset_id=progset.id, project_id=project.id)
    """
    class Meta:
        model = ProgramsDb

    progset_id = factory.LazyAttribute(lambda n: n)
    project_id = factory.LazyAttribute(lambda n: n)
    category = 'test'
    name = factory.Faker('name')
    short_name = factory.Faker('name')
    active = True
